name: Test
on:
  workflow_dispatch:
jobs:
  debug:
    runs-on: ubuntu-latest
    environment: andy-only
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: cli/cli

      - run: |
          gh pr checkout 10574
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - run: |
          make

      - run: bin/gh repo sync ${{github.repository}}
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_DEBUG: api
